test_dataset: 
  noisy_dir: ./prepare_datasets/DNS3/train_noisy/
  clean_dir: ./prepare_datasets/DNS3/train_clean/

network:
  exp_path: ./exp_gtcrn
  config: ${network.exp_path}/config.yaml
  ckpt_name: model_001
  checkpoint: ${network.exp_path}/checkpoints/${network.ckpt_name}.tar
  enh_folder: ${network.exp_path}/${network.ckpt_name}/enhanced
